version: "3"

services:
    node1:
        container_name: node1
        build:
            context: Node1
        command: python3 -u main.py
        volumes:
            - ./Node1:/app
        depends_on:
            - communitysolidserver
        network_mode: host
        #networks:
        #    - Node1CSS

    node2:
        container_name: node2
        build:
            context: Node2
        command: python3 -u main.py
        volumes:
            - ./Node2:/app
        depends_on:
            - communitysolidserver
        network_mode: host
        #networks:
        #    - Node2CSS

    communitysolidserver:
        image: solidproject/community-server:latest
        container_name: solid_server
        restart: unless-stopped
        network_mode: host
        #networks:
        #    - Node1CSS
        #    - Node2CSS
        env_file:
            - ./.env
        # ports:
        #     - 3000:3000
        volumes:
            - poddata:/poddata    # Volume for storing data
            - ./SolidServer/unsafe.json:/community-server/custom/unsafe.json    # Binding to read the config file
        command:
            - -c${CONFIG_PATH} # For some reason the server insert a space after -c and the path. Using the env interpolation like this allows to not have parsing errors

# networks:
#     Node1CSS:
#         driver: bridge
#     Node2CSS:
#         driver: bridge

volumes:
    poddata:
